/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestaoolz;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Guest
 */
public class fEditar2 extends javax.swing.JFrame {

    /**
     * Creates new form fEditar2
     */
    public fEditar2() {
        initComponents();
    }

    public fEditar2(String NomeLivro) {
        initComponents();
        txt_titulo.setText(NomeLivro);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(fEdita1.class.getName()).log(Level.SEVERE, null, ex);
        }

        Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/id22264273_bd_biblioteca", "root", "");

        } catch (SQLException ex) {
            Logger.getLogger(fEdita1.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (con != null) {
            String sql = "SELECT * FROM livro WHERE isbn='" + NomeLivro + "'";

            PreparedStatement preparedStatement;

            try {
                preparedStatement = con.prepareStatement(sql);
                ResultSet resultSet = preparedStatement.executeQuery();

                while (resultSet.next()) {
                    txt_isbn.setText(resultSet.getString(2));
                    txt_titulo.setText(resultSet.getString(3));
                    txt_autor.setText(resultSet.getString(4));
                    txt_paginas.setText(resultSet.getString(5));
                    txt_editora.setText(resultSet.getString(6));
                    txt_tamanho.setText(resultSet.getString(7));
                }
            } catch (SQLException ex) {
                Logger.getLogger(fEdita1.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Ligação realizada sem sucesso");
        }
    }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_isbn = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JTextField();
        txt_autor = new javax.swing.JTextField();
        txt_paginas = new javax.swing.JTextField();
        txt_editora = new javax.swing.JTextField();
        txt_tamanho = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Editar Livros");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 6, -1, -1));

        jLabel2.setText("isbn");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 40, -1, -1));

        jLabel3.setText("titulo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 88, -1, -1));

        jLabel4.setText("autor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 143, -1, -1));

        jLabel5.setText("n de paginas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel6.setText("editora");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel7.setText("tamanho");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));
        getContentPane().add(txt_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 120, -1));
        getContentPane().add(txt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 110, -1));
        getContentPane().add(txt_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 110, -1));
        getContentPane().add(txt_paginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 120, -1));
        getContentPane().add(txt_editora, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 120, -1));
        getContentPane().add(txt_tamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 110, -1));

        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        jButton2.setText("Voltar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // quando clico em alterar
        PreparedStatement pstmt = null;
        Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/id22264273_bd_biblioteca", "root", "");

        } catch (SQLException ex) {
            Logger.getLogger(fInserir.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (con != null) {

            //JOptionPane.showMessageDialog(null, "Ligação realizada com sucesso!");
            String isbn = this.txt_isbn.getText();
            String titulo = this.txt_titulo.getText();
            String autor = this.txt_autor.getText();
            int n_paginas = Integer.parseInt(this.txt_paginas.getText());
            String editora = this.txt_editora.getText();
            String tamanho = this.txt_tamanho.getText();

            String sql = "UPDATE livro SET titulo=?, autor=?, n_paginas=?,"
                    + "editora=?, tamanho=? WHERE isbn=?";
            try {
                pstmt = con.prepareStatement(sql);
                pstmt.setString(1, titulo);
                pstmt.setString(2, autor);
                pstmt.setInt(3, n_paginas);
                pstmt.setString(4, editora);
                pstmt.setString(5, tamanho);
                pstmt.setString(6, isbn);

                int rowsAffected = pstmt.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Registo alterado com sucesso!");
                    setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Falha ao atualizar o registo!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(fInserir.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if (pstmt != null) {
                        pstmt.close();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ligação realizada sem sucesso!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fEditar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fEditar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fEditar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fEditar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fEditar2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_editora;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_paginas;
    private javax.swing.JTextField txt_tamanho;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
